name: Build and Publish Docker Image

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/jonasborn/inquiro-fm:latest .

      # Step 4: Push the Docker image to the GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/jonasborn/inquiro-fm:latest
